print("Finally I felt the calming breeze \n stepping out to watch the final scene \n after all, it's you, my pride, and me \n I can't speak, whatever I can speak you see")
print("\n")
print("Hulk Like Real Fire.")
print(" A string is a secuence of characters, visible or unvisible \n it is also always in quatations")
print("an integer is a whole number and does not need quatations")
print("A float is a number that is a number but is not an integer,like 13.2")
print(543/3) 
print(int(543/3))
print(547%3)
print(1000%9)
print(int(434/10))
print(3%2)
print(5%5)
print(555/2)
print(123//2)
print(123%2)
print(764%2)
print(165//2)