print("questions 1-8")
print("Finally I felt the calming breeze \n stepping out to watch the final scene \n after all, it's you, my pride, and me \n I can't speak, whatever I can speak you see")
print("\n")
print("Hulk Like Real Fire.")
print("\n")
print(" A string is a secuence of characters, visible or unvisible \n it is also always in quatations")
print("\n")
print("an integer is a whole number and does not need quatations")
print("\n")
print("A float is a number that is a number but is not an integer,like 13.2")
print("\n")
print(543/3) 
print("\n")
print(int(543/3))
print("\n")
print(547%3)
print("questions 9-18")
print("\n")
print(1000%9)
print("\n")
print(int(434/10))
print("\n")
print(3%2)
print("\n")
print(5%5)
print("\n")
print(555/2)
print("\n")
print(123//2)
print("\n")
print(123%2)
print("\n")
print(764%2)
print("\n")
print(165//2)
print("\n")
print("questions 19-27")
print(5.4 + 2.6)
print("\n")
print(5+3)
print("\n")
print(5-3.5)
print("\n")
print(4.8-5)
print("\n")
print(6/2)
print("\n")
print(5*6.5)
print(5*50)
print("Emmanuel"*10)
print("Emmanuel\n"*10)
print("questions 28-31")
